// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotq2f7ok4XIjizGpc3zDOTvRTJAT3mQI',
    appId: '1:40963012007:web:aa8def3dbe1fcd9b383282',
    messagingSenderId: '40963012007',
    projectId: 'commute-connect',
    authDomain: 'commute-connect.firebaseapp.com',
    storageBucket: 'commute-connect.appspot.com',
    measurementId: 'G-LFC8JB7MLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2dX2xl4ZRDEJt2omd68iooW4Nc5oD6qI',
    appId: '1:40963012007:android:3c519f6686dc98a4383282',
    messagingSenderId: '40963012007',
    projectId: 'commute-connect',
    storageBucket: 'commute-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaP-SdOmZVpjLuGtSsb7XOwQ-G-XYwwG0',
    appId: '1:40963012007:ios:9a82227c431bc056383282',
    messagingSenderId: '40963012007',
    projectId: 'commute-connect',
    storageBucket: 'commute-connect.appspot.com',
    iosBundleId: 'com.example.commuteConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaP-SdOmZVpjLuGtSsb7XOwQ-G-XYwwG0',
    appId: '1:40963012007:ios:f58c94616eee44f0383282',
    messagingSenderId: '40963012007',
    projectId: 'commute-connect',
    storageBucket: 'commute-connect.appspot.com',
    iosBundleId: 'com.example.commuteConnect.RunnerTests',
  );
}
